Launching the blog
acf-sack/sack-blog pull request #35
Opened 2022-01-11 19:57 UTC by Hasthikagirihagama

## Purpose

The purpose of this PR is to fix #33 

## Goals

Complete the following tasks
 - Remove dummy data
 - Connect with prose.io
 - Give credentials to media unit 
 - Launch the blog
 - Add navbar

## Approach

- [x] Remove dummy data
- [x] Connect with prose.io
- [x] Give credentials to media unit 
- [x] Launch the blog
- [x] Add navbar

### Screenshots

https://user-images.githubusercontent.com/70457601/149011901-a08a11ea-3b21-4529-ac5a-5c2f7c3c3a91.mov

  
### Preview Link
https://hasthikagirihagama.github.io/sack-blog/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2022-01-26 06:02 UTC, jayasanka-sack commented on _includes/footer.html
> +
```suggestion

```

2022-01-26 06:02 UTC, jayasanka-sack commented on _includes/navigation.html
> +
```suggestion
  </script>

```

2022-01-26 06:03 UTC, jayasanka-sack commented on _includes/navigation.html
> +
Oh, where this script tag comes from? 🤔

2022-01-28 05:23 UTC, jayasanka-sack requested changes
Good job @Hasthikagirihagama ! Don't forget to add a new line at the end of the files. ;)

2022-01-28 05:23 UTC, jayasanka-sack commented on _includes/footer.html
> +  <!-- //Footer -->
Alway's add a blank line at the end of files

2022-01-28 05:23 UTC, jayasanka-sack commented on _includes/navigation.html
> +  </script>
there is no opening <script> tag right? Seems like a mistake.

2022-01-29 10:30 UTC, Hasthikagirihagama commented
I think now all the changes are done @jayasanka-sack

2022-02-05 05:30 UTC, jayasanka-sack commented on _includes/navigation.html
> +
```suggestion

```

2022-02-05 05:30 UTC, jayasanka-sack commented on _includes/navigation.html
> +  <!-- //Navbar -->
```suggestion
  <!-- //Navbar -->

```

2022-02-05 05:31 UTC, jayasanka-sack approved these changes
Thanks @Hasthikagirihagama !

2022-02-05 05:31 UTC, merged